
# ------------------------------------------------------------
# Querying and Managing Relational Databases in R using SQLite
# ------------------------------------------------------------

# Install required packages (run once if not installed)
if(!require(DBI)) install.packages("DBI")
if(!require(dplyr)) install.packages("dplyr")
if(!require(RSQLite)) install.packages("RSQLite")

# Load libraries
library(DBI)
library(dplyr)
library(RSQLite)

# ------------------------------------------------------------
# Connect to SQLite database
# ------------------------------------------------------------
con <- dbConnect(RSQLite::SQLite(), "songs.db")

# ------------------------------------------------------------
# Check if 'songs' table exists, if not create it
# ------------------------------------------------------------
tables <- dbListTables(con)

if(!"songs" %in% tables){
  
  dbExecute(con,"
  CREATE TABLE songs (
    song_id INTEGER,
    title TEXT,
    artist_id INTEGER
  )
  ")
  
  dbExecute(con,"
  INSERT INTO songs VALUES
  (1,'Bohemian Rhapsody',11),
  (2,'We Will Rock You',11),
  (3,'We Are The Champions',11),
  (4,'Another One Bites The Dust',11),
  (5,'Radio Ga Ga',11),
  (6,'Random Song',5),
  (7,'Another Song',8)
  ")
}

# ------------------------------------------------------------
# Create reference to songs table
# ------------------------------------------------------------
songs_table <- tbl(con, "songs")

# ------------------------------------------------------------
# Query songs where artist_id = 11 (Queen)
# ------------------------------------------------------------
queen_songs <- songs_table %>%
  filter(artist_id == 11) %>%
  select(title)

# ------------------------------------------------------------
# Display SQL query generated by dplyr
# ------------------------------------------------------------
show_query(queen_songs)

# ------------------------------------------------------------
# Retrieve results into R
# ------------------------------------------------------------
result <- collect(queen_songs)

# Display results
print(result)

# ------------------------------------------------------------
# Disconnect from database
# ------------------------------------------------------------
dbDisconnect(con)

